stages:
  - prepare
  - migrations

default:
  interruptible: true
  timeout: 90m

variables:
  RAILS_ENV: "test"
  GL_REPO: "/gitlab"
  IMAGE_NAME: "gitlab-com-migrations:${GL_SHA}"

.image:base:
  stage: prepare
  tags:
    - builder

image:gitlab:
  extends: .image:base
  script:
    - docker build --build-arg GL_SHA=${GL_SHA} -t ${IMAGE_NAME} docker/gitlab
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}

image:dblab-ssh:
  extends: .image:base
  variables:
    IMAGE_NAME: "gitlab-com-migrations-dblab-ssh:latest"
  script:
    - docker build -t ${IMAGE_NAME} docker/dblab-ssh
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}

image:redis:
  extends: .image:base
  variables:
    IMAGE_NAME: "redis:4.0-alpine"
  script:
    - docker pull $IMAGE_NAME
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}

db:status:
  stage: migrations
  image: ${DOCKER_REGISTRY}/$IMAGE_NAME
  tags:
    - worker
  variables:
    DBLAB_HOST_KEYS: $DBLAB_HOST_KEYS
    DBLAB_SSH_KEY: $DBLAB_SSH_KEY
    DBLAB_TOKEN: $DBLAB_TOKEN
    DBLAB_USER: $DBLAB_USER
    DBLAB_PASSWORD: $DBLAB_PASSWORD
    DBLAB_ENVIRONMENT: $DBLAB_ENVIRONMENT
  services:
    - name: ${DOCKER_REGISTRY}/gitlab-com-migrations-dblab-ssh:latest
      alias: postgres
    - name: ${DOCKER_REGISTRY}/redis:4.0-alpine
      alias: redis
  artifacts:
    paths:
      - artifacts
    expire_in: 1 week
  script:
    - cd ${GL_REPO}
    - ./prepare.sh
    - bundle exec rake gitlab:db:migration_testing
    - cd ${CI_PROJECT_DIR}
    - mkdir -p artifacts; mv ${GL_REPO}/tmp/migration-stats.json artifacts
