stages:
  - prepare
  - migrations

default:
  interruptible: true
  timeout: 90m

variables:
  RAILS_ENV: "test"
  BUILD_PATH: "/builds/gitlab"
  GL_REPO: "/repos/gitlab"
  IMAGE_NAME: "gitlab-com-migrations:${GL_SHA}"

.image:base:
  stage: prepare
  tags:
    - builder

image:gitlab:
  extends: .image:base
  script:
    - mkdir -p /docker-builds
    - echo Building ${IMAGE_NAME}
    - docker build --build-arg GL_SHA=${GL_SHA} -t ${IMAGE_NAME} .
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}:${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}:${IMAGE_NAME}

image:redis:
  extends: .image:base
  variables:
    IMAGE_NAME: "redis:4.0-alpine"
  script:
    - mkdir -p /docker-builds
    - docker pull $IMAGE_NAME
    - docker tag -t ${DOCKER_REGISTRY}:${IMAGE_NAME} ${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}:${IMAGE_NAME}

image:postgres:
  extends: .image:base
  variables:
    IMAGE_NAME: "postgres:11.6"
  script:
    - mkdir -p /docker-builds
    - docker pull $IMAGE_NAME
    - docker tag -t ${DOCKER_REGISTRY}:${IMAGE_NAME} ${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}:${IMAGE_NAME}

db:status:
  stage: migrations
  image: $IMAGE_NAME
  tags:
    - worker
  services:
    - name: postgres:11.6
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    - name: redis:4.0-alpine
  variables:
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - env
    - ls -l
    - source scripts/utils.sh
    - source scripts/prepare_build.sh
    - rake db:migrate:status
