stages:
  - prepare
  - migrations

default:
  image: "registry.gitlab.com/gitlab-org/gitlab-build-images:ruby-2.7.2-golang-1.14-git-2.29-lfs-2.9-chrome-85-node-12.18-yarn-1.22-postgresql-11-graphicsmagick-1.3.34"
  interruptible: true
  timeout: 90m

variables:
  RAILS_ENV: "test"
  BUILD_PATH: "/builds/gitlab"
  GL_REPO: "/repos/gitlab"
  IMAGE_NAME: "gitlab-com-migrations:${GL_SHA}"

build:image:
  stage: prepare
  script:
    - docker build --build-arg GL_SHA=${GL_SHA} -t ${IMAGE_NAME} .

db:migrations:
  stage: migrations
  image: $IMAGE_NAME
  services:
    - name: postgres:11.6
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    - name: redis:4.0-alpine
  variables:
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - env
    - ls -l
    - source scripts/utils.sh
    - source scripts/prepare_build.sh
    - rake db:migrate:status
