stages:
  - prepare
  - migrations

default:
  interruptible: true
  timeout: 90m

variables:
  RAILS_ENV: "test"
  BUILD_PATH: "/builds/gitlab"
  GL_REPO: "/repos/gitlab"
  IMAGE_NAME: "gitlab-com-migrations:${GL_SHA}"

build:image:
  stage: prepare
  tags:
    - docker
  script:
    - docker build --build-arg GL_SHA=${GL_SHA} -t ${IMAGE_NAME} .

db:migrations:
  stage: migrations
  image: $IMAGE_NAME
  tags:
    - dblab
  services:
    - name: postgres:11.6
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    - name: redis:4.0-alpine
  variables:
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - env
    - ls -l
    - source scripts/utils.sh
    - source scripts/prepare_build.sh
    - rake db:migrate:status
