stages:
  - migrations

default:
  image: "registry.gitlab.com/gitlab-org/gitlab-build-images:ruby-2.7.2-golang-1.14-git-2.29-lfs-2.9-chrome-85-node-12.18-yarn-1.22-postgresql-11-graphicsmagick-1.3.34"
  interruptible: true
  timeout: 90m

.rails-cache:
  cache:
    key: "rails-v3"
    paths:
      - vendor/ruby/
      - vendor/gitaly-ruby/
      - .go/pkg/mod/
    policy: pull

.default-before_script:
  before_script:
    - export GOPATH=$CI_PROJECT_DIR/.go
    - mkdir -p $GOPATH
    - source scripts/utils.sh
    - source scripts/prepare_build.sh

variables:
  RAILS_ENV: "test"

db:migrations:
  extends: .default-before_script
  stage: migrations
  services:
    - name: postgres:11.6
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    - name: redis:4.0-alpine
  variables:
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - echo ${CI_PROJECT_DIR}
    - git clone https://gitlab.com/gitlab-org/gitlab.git ${CI_PROJECT_DIR}
    - cd ${CI_PROJECT_DIR}
    - env
    - rake db:migrate:status
