stages:
  - prepare
  - test
  - final

default:
  timeout: 300m

variables:
  RAILS_ENV: "test"
  GITLAB_PATH: "/gitlab"
  GITLAB_COMMIT_SHA: "master"
  IMAGE_NAME: "gitlab-com-database-testing:${GITLAB_COMMIT_SHA}"

.image:base:
  stage: prepare
  tags:
    - builder

image:gitlab:
  extends: .image:base
  script:
    - docker build --build-arg GITLAB_COMMIT_SHA=${GITLAB_COMMIT_SHA} -t ${IMAGE_NAME} docker/gitlab
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}

image:dblab-ssh:
  extends: .image:base
  variables:
    IMAGE_NAME: "gitlab-com-database-testing-dblab-ssh:latest"
  script:
    - docker build -t ${IMAGE_NAME} docker/dblab-ssh
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}

image:redis:
  extends: .image:base
  variables:
    IMAGE_NAME: "redis:4.0-alpine"
  script:
    - docker pull $IMAGE_NAME
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}

db:migrations:
  stage: test
  image: ${DOCKER_REGISTRY}/$IMAGE_NAME
  tags:
    - worker
  variables:
    DBLAB_HOST_KEYS: $DBLAB_HOST_KEYS
    DBLAB_SSH_KEY: $DBLAB_SSH_KEY
    DBLAB_TOKEN: $DBLAB_TOKEN
    DBLAB_USER: $DBLAB_USER
    DBLAB_PASSWORD: $DBLAB_PASSWORD
    DBLAB_ENVIRONMENT: $DBLAB_ENVIRONMENT
    DBLAB_CLONE_ID: "database-testing-${CI_PIPELINE_ID}"
  services:
    - name: ${DOCKER_REGISTRY}/gitlab-com-database-testing-dblab-ssh:latest
      alias: postgres
    - name: ${DOCKER_REGISTRY}/redis:4.0-alpine
      alias: redis
  artifacts:
    paths:
      - migration-stats.json
      - migrations.json
    expire_in: 4 weeks
    when: always
  when: manual
  allow_failure: true
  script:
    - cd ${GITLAB_PATH}
    - ./prepare.sh
    - bundle exec ruby list-migrations.rb > ${CI_PROJECT_DIR}/migrations.json
    - bundle exec rake gitlab:db:migration_testing[${CI_PROJECT_DIR}/migration-stats.json]

notify-upstream:
  stage: final
  tags:
    - builder
  needs:
    - job: db:migrations
      artifacts: true
  # Also store artifacts here so we can easily generate direct links to them
  artifacts:
    paths:
      - migration-stats.json
      - migrations.json
    expire_in: 4 weeks
    when: always
  script:
    - cd notifier
    - bundle install
    - bundle exec ruby notifier.rb send ../migration-stats.json ../migrations.json
