stages:
  - prepare
  - migrations

default:
  interruptible: true
  timeout: 90m

variables:
  RAILS_ENV: "test"
  BUILD_PATH: "/builds/gitlab"
  GL_REPO: "/repos/gitlab"
  IMAGE_NAME: "gitlab-com-migrations:${GL_SHA}"

.image:base:
  stage: prepare
  tags:
    - builder

image:gitlab:
  extends: .image:base
  script:
    - echo Building ${IMAGE_NAME}
    - docker build --build-arg GL_SHA=${GL_SHA} -t ${IMAGE_NAME} docker/gitlab
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}

image:dblab-ssh:
  extends: .image:base
  variables:
    IMAGE_NAME: "gitlab-com-migrations-dblab-ssh:latest"
  script:
    - echo Building ${IMAGE_NAME}
    - docker build -t ${IMAGE_NAME} docker/dblab-ssh
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}

image:redis:
  extends: .image:base
  variables:
    IMAGE_NAME: "redis:4.0-alpine"
  script:
    - docker pull $IMAGE_NAME
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}

image:postgres:
  extends: .image:base
  variables:
    IMAGE_NAME: "postgres:11.6"
  script:
    - docker pull $IMAGE_NAME
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}

db:status:
  stage: migrations
  image: ${DOCKER_REGISTRY}/$IMAGE_NAME
  tags:
    - worker
  services:
    - name: ${DOCKER_REGISTRY}/gitlab-com-migrations-dblab-ssh:latest
      alias: postgres
    - name: ${DOCKER_REGISTRY}/redis:4.0-alpine
      alias: redis
  variables:
    DBLAB_SSH_KEY: ""
    DBLAB_HOST_KEYS: ""
    DBLAB_USER: ""
    DBLAB_PASSWORD: ""
    DBLAB_SSH_HOST: ""
    DBLAB_ENVIRONMENT: ""
    DBLAB_TOKEN: ""
  script:
    - env
    - ls -l
    - ./prepare.sh
    - cat config/database.yml
    - curl -v https://google.com
    - rake db:migrate:status
