stages:
  - migrations

default:
  image: "registry.gitlab.com/gitlab-org/gitlab-build-images:ruby-2.7.2-golang-1.14-git-2.29-lfs-2.9-chrome-85-node-12.18-yarn-1.22-postgresql-11-graphicsmagick-1.3.34"
  interruptible: true
  timeout: 90m

.default-before_script:
  cache:
    key: 'gl-repo'
    paths:
      - ${GL_REPO}
    policy: pull
  before_script:
    - echo ${BUILD_PATH}
    - if [ ! -d ${GL_REPO} ]; then
        rm -rf ${BUILD_PATH};
        git clone --progress --no-checkout https://gitlab.com/gitlab-org/gitlab.git ${GL_REPO};
        git clone ${GL_REPO} ${BUILD_PATH}
      fi
    - cd ${BUILD_PATH}
    - export GOPATH=$BUILD_PATH/.go
    - mkdir -p $GOPATH
    - echo 'TODO: update code'
    - ls -l
    - source scripts/utils.sh
    - source scripts/prepare_build.sh

variables:
  RAILS_ENV: "test"
  BUILD_PATH: "/builds/gitlab"
  GL_REPO: "/repos/gitlab"

db:migrations:
  extends: .default-before_script
  stage: migrations
  services:
    - name: postgres:11.6
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    - name: redis:4.0-alpine
  variables:
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - env
    - rake db:migrate:status
