stages:
  - prepare
  - test
  - final

default:
  timeout: 300m

variables:
  RAILS_ENV: "test"
  GITLAB_PATH: "/gitlab"
  GITLAB_COMMIT_SHA: "master"
  IMAGE_NAME: "gitlab-com-database-testing:${GITLAB_COMMIT_SHA}"
  UPSTREAM_GIT_URL: https://gitlab.com/gitlab-org/gitlab.git

.image:base:
  stage: prepare
  tags:
    - builder

image:gitlab:
  extends: .image:base
  script:
    - docker build --build-arg GITLAB_COMMIT_SHA=${GITLAB_COMMIT_SHA} --build-arg UPSTREAM_GIT_URL=${UPSTREAM_GIT_URL} -t ${IMAGE_NAME} docker/gitlab
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}

image:dblab-ssh:
  extends: .image:base
  variables:
    IMAGE_NAME: "gitlab-com-database-testing-dblab-ssh:latest"
  script:
    - docker build -t ${IMAGE_NAME} docker/dblab-ssh
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}

image:redis:
  extends: .image:base
  variables:
    IMAGE_NAME: "redis:4.0-alpine"
  script:
    - docker pull $IMAGE_NAME
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}

db:migrations:
  stage: test
  image: ${DOCKER_REGISTRY}/$IMAGE_NAME
  tags:
    - worker
  variables:
    DBLAB_HOST_KEYS: $DBLAB_HOST_KEYS
    DBLAB_SSH_KEY: $DBLAB_SSH_KEY
    DBLAB_TOKEN: $DBLAB_TOKEN
    DBLAB_USER: $DBLAB_USER
    DBLAB_PASSWORD: $DBLAB_PASSWORD
    DBLAB_API_PORT: $DBLAB_API_PORT
    DBLAB_API_PORT_CI: $DBLAB_API_PORT_CI
    DBLAB_ENVIRONMENT: $DBLAB_ENVIRONMENT
    DBLAB_ENVIRONMENT_CI: $DBLAB_ENVIRONMENT_CI
    ALL_DB_HOSTS: "postgres-main,postgres-ci"
    DBLAB_CLONE_ID: "database-testing-${CI_PIPELINE_ID}-${CI_JOB_ID}"
  services:
    - name: ${DOCKER_REGISTRY}/gitlab-com-database-testing-dblab-ssh:latest
      alias: postgres-main
      variables:
        DBLAB_CLONE_ID: "database-testing-${CI_PIPELINE_ID}-${CI_JOB_ID}-main"
    - name: ${DOCKER_REGISTRY}/gitlab-com-database-testing-dblab-ssh:latest
      alias: postgres-ci
      variables:
        DBLAB_CLONE_ID: "database-testing-${CI_PIPELINE_ID}-${CI_JOB_ID}-ci"
        DBLAB_ENVIRONMENT: $DBLAB_ENVIRONMENT_CI
        DBLAB_API_PORT: $DBLAB_API_PORT_CI
    - name: ${DOCKER_REGISTRY}/redis:4.0-alpine
      alias: redis
  artifacts:
    paths:
      - migration-testing/
    expire_in: 4 weeks
    when: always
  allow_failure: true
  script:
    - cd ${GITLAB_PATH}
    - ./prepare.sh
    - mkdir -p tmp/migration-testing/main/up
    - mkdir -p tmp/migration-testing/ci/up
    - mkdir -p tmp/migration-testing/main/background_migrations
    - mkdir -p tmp/migration-testing/ci/background_migrations
    - bundle exec rake gitlab:db:migration_testing:up:main | tee tmp/migration-testing/main/up/full-migration-output.log || true
    - bundle exec rake gitlab:db:migration_testing:up:ci | tee tmp/migration-testing/ci/up/full-migration-output.log || true
    - bundle exec rake gitlab:db:migration_testing:sample_background_migrations | tee tmp/migration-testing/background_migrations/full-migration-output.log || true
    - bundle exec rake gitlab:db:migration_testing:sample_batched_background_migrations:main | tee tmp/migration-testing/main/background_migrations/full-batched-migration-output.log || true
    - bundle exec rake gitlab:db:migration_testing:sample_batched_background_migrations:ci | tee tmp/migration-testing/ci/background_migrations/full-batched-migration-output.log || true
    - mv tmp/migration-testing/ ${CI_PROJECT_DIR}
    - bundle exec ruby list_migrations.rb > ${CI_PROJECT_DIR}/migration-testing/migrations.json
    - bundle exec ruby clone_details.rb > ${CI_PROJECT_DIR}/migration-testing/clone-details.json

notify-upstream:
  stage: final
  tags:
    - builder
  # Also store artifacts here so we can easily generate direct links to them
  artifacts:
    paths:
      - migration-testing/
    expire_in: 4 weeks
    when: always
  script:
    - cd notifier
    - bundle install
    - bundle exec ruby notifier.rb send ../migration-testing/
