# frozen_string_literal: true
source 'https://rubygems.org'

gem 'activesupport'
gem 'filesize'
gem 'gitlab'
gem 'gitlab-styles', require: false
gem 'niceql'
gem 'pg_query'
gem 'pry'
gem 'thor'
gem 'activesupport'

group :test do
  gem 'rspec'
  gem 'rspec_junit_formatter'
  gem 'rubocop'
end
